#!/bin/bash

entries="Logout Suspend Reboot Shutdown"

selected=$(printf '%s\n' $entries | wofi -dmenu -c $XDG_CONFIG_HOME/wofi/config -s $XDG_CONFIG_HOME/wofi/style.css | awk '{print tolower($1)}')

case $selected in
  logout)
    hyprctl --instance 0 dispatch 'hl.dsp.exit()';;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
