-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: preload = "/usr/share/hypr/wall2.png"

--wallpaper = monitor, /usr/share/hypr/wall2.png

hl.config({
    wallpaper = {
        path = "/usr/share/hypr/wall2.png",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output

hl.config({
    wallpaper = {
        path = "/usr/share/hypr/wall2.png",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output
