---@module 'hl'

-- #######################################################################################

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- DEBUG 
--debug:disable_logs = false
-- https://wiki.hypr.land/Configuring/
--
--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

--monitor=,preferred,auto,auto

hl.monitor({
    output   = "DP-1",
    mode     = "3840x216@1440",
    position = "0x0",
    scale    = 1,
})

local mainMonitor = "DP-1"

--workspace = DP-1,1

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60",
    position = "3840x0",
    scale    = 1,
})

local secondaryMonitor = "HDMI-A-1"

--workspace = HDMI-A-1,6

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

--$terminal = kitty

local terminal = "alacritty"

local fileManager = "dolphin"

local menu = "wofi --show drun -c $XDG_CONFIG_HOME/wofi/config -s $XDG_CONFIG_HOME/wofi/style.css"

local browser = "brave"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:


-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox





--exec-once = solaar -w show -b symbolic



--exec-once = [workspace 0 silent] QOwnNotes

--exec-once = QOwnNotes




-- 1. Open App 3 (The full-height uindow)

--exec-once = [workspace 10 silent] Telegram

--exec-once = Telegram

-- 2. Open App 1

--exec-once = [workspace 10 silent] keepassxc

--exec-once = keepassxc

-- 3. Open App 2 (This will split the remaining space with App 1)

--exec-once = [workspace 10 silent] QOwnNotes

--exec-once = QOwnNotes

--############################

--## OSD (SYSHUD)          ###

--############################


--############################

--## LIGHT FILTER          ###

--############################


--############################

--## LOCKSCREEN            ###

--############################

--exec-once = swayidle -w


--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRAY_NAME", "nvidia")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("GBM_BACKEND", "nvidia-drm")

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 2,
        border_size = 1,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 2,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/ for more
    },
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        -- pseudotile = true,
        -- Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "it",
        -- kb_variant = {  },
        -- kb_model = {  },
        -- kb_options = {  },
        -- kb_rules = {  },
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#gestures

--gestures {

--    workspace_swipe = false

--}

-- https://wiki.hypr.land/Configuring/Gestures/

-- Replaced on update 5.5.1

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("alacritty"))

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("alacritty"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("brave"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ESCAPE", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("wofi --show drun -c $XDG_CONFIG_HOME/wofi/config -s $XDG_CONFIG_HOME/wofi/style.css"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

-- hl.bind(mainMod .. " + " .. "J", hl.dsp.layout(nil))
hl.bind(mainMod .. " + J", function()
    hl.dispatch("layoutmsg", "togglesplit")
end)

-- dwindle

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("hyprpicker"))

-- Scripts launch from bindings

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("~/.config/hypr/scripts/launch-waybar"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move windows with mainMod + arrows keys

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", { direction = "l" })
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", { direction = "r" })
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", { direction = "u" })
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", { direction = "d" })

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left"}))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right"}))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up"}))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down"}))

-- Resize window with mainMod + CTRL + arrow keys
-- Press ALT + R and arrow key to resize current window, press escape to exit from submap and finish resizing mode
-- Switch to a submap called `resize`.
hl.bind("ALT + R", hl.dsp.submap("resize"))

-- Start a submap called "resize".
hl.define_submap("resize", function()

    -- Set repeating binds for resizing the active window.
    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true}), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true}), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = 10, relative = true}), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = -10, relative = true}), { repeating = true })

    -- Use `reset` to go back to the global submap
    hl.bind("escape", hl.dsp.submap("reset"))

end)

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#########################
--
--## ANIMATION SETTINGS ###
--
--#########################

hl.animation({ leaf = "global",        enabled = true,  speed = 3.0,   bezier = "default" })



--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.

-- hl.window_rule({
--    name  = "suppress_event_maxim",
--    match = {
--        match = "class .*",
--    },
--    -- TODO: review rule: "suppress_event maximize"
-- })

-- Fix some dragging issues with XWayland

-- hl.window_rule({
--     name  = "no_focus_on",
--     match = {
--         match = "pin 0",
--     },
--     -- TODO: review rule: "no_focus on"
-- })

--workspace=1, monitor:DP-1

--workspace=2, monitor:DP-1

--workspace=3, monitor:DP-1

--workspace=4, monitor:DP-1

--workspace=5, monitor:DP-1

--workspace=6, monitor:HDMI-A-1

--workspace=7, monitor:HDMI-A-1

--workspace=8, monitor:HDMI-A-1

--workspace=9, monitor:HDMI-A-1

--workspace=10, monitor:HDMI-A-1

--workspace = r[1-5], monitor:$mainMonitor, default:true

--workspace = r[6-0], monitor:$secondaryMonitor, default:true

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 9,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 10,
    monitor = "HDMI-A-1",
})

-- CUSTOM WINDOWS RULES

-- Dynamically generate routing rules for Brave windows titled (1) through (10)
for i = 1, 10 do
    hl.window_rule({
        name  = "workspace_" .. i .. "_silent",
        match = {
            class = "brave-browser",
            title = "^(" .. i .. ")", -- Mirroring your exact working config syntax
        },
        workspace = i .. " silent",
    })
end

hl.window_rule({
    name      = "workspace_10_apps_silent",
    match = {
        class = "^(org.telegram.desktop|PBE.QOwnNotes|org.keepassxc.KeePassXC|solaar)$",
    },
    workspace = "10 silent",
})




-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("dunst")
    hl.exec_cmd("copyq --start-server")
    hl.exec_cmd("solaar -w hide -b symbolic")
    hl.exec_cmd("brave --profile-directory=Default --hide-crash-restore-bubble --restore-last-session")
    hl.exec_cmd("Telegram")
    hl.exec_cmd("QOwnNotes")
    hl.exec_cmd("keepassxc")
    hl.exec_cmd("syshud")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hypridle")
end)
