-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        -- avoid starting multiple hyprlock instances.
        before_sleep_cmd = "loginctl lock-session",
        -- lock before suspend.
        after_sleep_cmd = "hyprctl dispatch dpms on",
        -- to avoid having to press a key twice to turn on the display.
    },
})

hl.config({
    listener = {
        timeout = 150,
        -- 2.5min.
        on-timeout = "brightnessctl -s set 10",
        -- set monitor backlight to minimum, avoid 0 on OLED monitor.
        on-resume = "brightnessctl -r",
        -- monitor backlight restore.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.

hl.config({
    listener = {
        timeout = 150,
        -- 2.5min.
        on-timeout = "brightnessctl -sd rgb:kbd_backlight set 0",
        -- turn off keyboard backlight.
        on-resume = "brightnessctl -rd rgb:kbd_backlight",
        -- turn on keyboard backlight.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 300,
        -- 5min
        on-timeout = "loginctl lock-session",
        -- lock screen when timeout has passed
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 330,
        -- 5.5min
        --on-timeout = hyprctl dispatch dpms off                    # screen off when timeout has passed
        on-timeout = "hyprctl dispatch dpms idle",
        -- screen off when timeout has passed
        on-resume = "hyprctl dispatch dpms on && brightnessctl -r",
        -- screen on when activity is detected after timeout has fired.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 600,
        -- 10min
        on-timeout = "systemctl suspend",
        -- suspend pc
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
